# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 04:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('updated_at', models.CharField(blank=True, max_length=150, null=True)),
                ('company_profile', models.CharField(blank=True, max_length=150, null=True)),
                ('purpose', models.CharField(blank=True, max_length=150, null=True)),
                ('x', models.CharField(blank=True, max_length=50, null=True)),
                ('xii', models.CharField(blank=True, max_length=50, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('a_backlog', models.CharField(blank=True, max_length=50, null=True)),
                ('t_backlog', models.CharField(blank=True, max_length=50, null=True)),
                ('ppt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_date', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_issue_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('willingness_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('btech_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('idd_imd_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('jd', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
