# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('company_profile', models.CharField(blank=True, max_length=150, null=True)),
                ('purpose', models.CharField(blank=True, max_length=150, null=True)),
                ('x', models.CharField(blank=True, max_length=10, null=True)),
                ('xii', models.CharField(blank=True, max_length=10, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('a_backlog', models.CharField(blank=True, max_length=10, null=True)),
                ('t_backlog', models.CharField(blank=True, max_length=10, null=True)),
                ('ppt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_date', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_issue_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('willingness_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('btech_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('idd_imd_ctc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
