# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
