# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='None', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
