# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170714_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
