# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.CharField(blank=True, default='internship', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
