# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 14:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170714_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
