# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20170714_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucker',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sucker',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
