# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20170714_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sucker',
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
