# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20170715_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subsribe',
            field=models.BooleanField(default=True),
        ),
    ]
