# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_user_subsribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subsribe',
            new_name='subsribed',
        ),
    ]
