# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20170715_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subsribed',
            new_name='subscribed',
        ),
    ]
