# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 10:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20170716_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jd',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
